title: Blog
#description: My Personal Stack Problems
author: Isaac Andrés
github: https://github.com/IsaacAndres
about: Desarrollador Web / PHP CodeIgniter
#disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: https://avatars3.githubusercontent.com/u/14645164?v=4&s=460

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: "#"
    #- icon: fa-twitter
    #  link: "https://twitter.com/Ragnardxc"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/isaac-figueroa"
    #- icon: fa-stack-exchange
    #  link: "#"
    - icon: fa-github
      link: "https://github.com/IsaacAndres"
    - icon: fa-github
      link: "https://gist.github.com/IsaacAndres"

share:
  twitter_username: Ragnardxc
  #fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
    #  url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://isaacandres.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
